# Configuration for Issue States - https://github.com/dessant/issue-states

# Open issues that are moved to these project columns. Set to `[]` to disable
openIssueColumns: 
  - To do
  - In progress
# Close issues that are moved to these project columns. Set to `[]` to disable
closedIssueColumns:
  - Done
