name: Publish latest Docker image
on:
  push
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: echo tag_name
        run: echo "${{ github.event.release.tag_name }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: f1nnm/yacahc:latest
          context: ./frontend
          push: true
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: f1nnm/yacahc_backend:latest
          context: ./backend
          push: true
